### ISSUE TITLE
解析包出现问题不能安装4.6.6版本

### ISSUE THREAD

**Issue by 973585899** [Xposed-Modules-Repo/com.coderstory.flyme10#2]
打开后就不能安装
![S30702-07051919](https://github.com/Xposed-Modules-Repo/com.coderstory.flyme10/assets/32036760/e3ad2fdb-a66e-4e12-9c83-effa05879048)
![S30702-07060153](https://github.com/Xposed-Modules-Repo/com.coderstory.flyme10/assets/32036760/4f492f34-d905-4131-8fc1-e63644c990b0)

**Comment by coderstory** [comment]
好像被我改成只支持13了 比较flyme10 就只有Android 13
